apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-mlm-ui
  namespace: csi-perf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csi-mlm-ui
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: csi-mlm-ui
        module: adt
        tier: frontend
        track: stable
    spec:
      containers:
        - image: harbor.cs.local/vidaplus/mlm-ui:4.4.100.0
          imagePullPolicy: IfNotPresent
          name: csi-mlm-ui
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 2m
              memory: 25Mi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-mlm-ui-service
  name: csi-mlm-ui-service
  namespace: csi-perf
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-mlm-ui
  type: ClusterIP
