---
apiVersion: v1
kind: Service
metadata:
  name: csi-support-portal-service
  namespace: csi-perf
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: csi-support-portal
  type: ClusterIP