---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-ie-general
  name: csi-ie-general
  namespace: csi-perf
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-ie-general
  type: ClusterIP
