apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-ie-general
  namespace: csi-perf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-ie-general
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-ie-general
        module: integration
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: configserver
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
            - name: active_profile
              valueFrom:
                configMapKeyRef:
                  key: activeProfile
                  name: service-configs
            - name: hostname
              value: csi-ie-general
          envFrom:
            - configMapRef:
                name: service-configs
            - secretRef:
                name: service-configs-secret
            - configMapRef:
                name: service-configs-integration
            - secretRef:
                name: service-integration-secret
          image: harbor.cs.local/vidaplus/csi-ie-general:4.1.136.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: http
            initialDelaySeconds: 600
            periodSeconds: 10
          name: csi-ie-general
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
          volumeMounts:
            - mountPath: /app/config
              name: config-vol
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: config-vol
          projected:
            sources:
              - secret:
                  name: service-cas-credential-secret
              - secret:
                  name: service-sickleave-credential-secret

