---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-ehr-ic-ui-service
  name: csi-ehr-ic-ui-service
  namespace: vidacom
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-ehr-ic-ui
  type: ClusterIP
