apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-rms-morgue
  namespace: csi-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: csi-rms-morgue
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-rms-morgue
        module: rms
        tier: backend
        track: stable
    spec:
      containers:
          image: >-
            harbor.cs.local/vidaplus/csi-rms-morgue-java-service:4.1.1.0-a82
          ports:
            - containerPort: 80
              name: http
