apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-bloodbank-ui
  namespace: vidacom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-bloodbank-ui
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: csi-bloodbank-ui
        module: bloodbank
        tier: frontend
        track: stable
    spec:
      containers:
        - image: harbor.cs.local/vidaplus/bloodbank-ui:4.1.1.1
          imagePullPolicy: IfNotPresent
          name: csi-bloodbank-ui
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 25m
              memory: 256Mi
      imagePullSecrets:
        - name: regcred

