apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-approval-ui
  namespace: csi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-approval-ui
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: csi-approval-ui
        module: billing
        tier: frontend
        track: stable
    spec:
      containers:
        - image: harbor.cs.local/vidaplus/approval-ui:4.3.26.0
          imagePullPolicy: IfNotPresent
          name: csi-approval-ui
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 25m
              memory: 256Mi
      imagePullSecrets:
        - name: regcred