apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-phr-base
  name: csi-phr-base-canary
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-phr-base
  type: ClusterIP
    # This selector will be updated with the pod-template-hash of the canary ReplicaSet. e.g.:
    # rollouts-pod-template-hash: 7bf84f9696

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-phr-base
  name: csi-phr-base
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-phr-base
  type: ClusterIP
    # This selector will be updated with the pod-template-hash of the stable ReplicaSet. e.g.:
    # rollouts-pod-template-hash: 789746c88d