apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app-ui
  namespace: prod-tech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-app-ui
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: healthcare-app-ui
        module: adt
        tier: frontend
        track: stable
    spec:
      containers:
        - image: lexuanthinh/pharmacy-user:5.2 #velickotam/healthcaresystem:vue_latest
          imagePullPolicy: IfNotPresent
          name: healthcare-app-ui
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 25m
              memory: 256Mi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: healthcare-app-ui
  name: healthcare-app-ui
  namespace: prod-tech
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: healthcare-app-ui
  type: ClusterIP
