apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
#resources:
#- rollout-csi-net-bloodbnk.yaml
#- rollout-csi-bloodbank-ui-rollout-csi-net-bloodbnk-service.yaml

patchesStrategicMerge:
- replica-count1.yaml

images:
- name: harbor.cs.local/vidaplus/csi-iam
  newTag: 4.2.90.1

patchesJson6902:
- target:
    version: apps/v1
    kind: Deployment
    name: csi-iam
  path: patch.yaml