apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-iam
  namespace: csi-perf
spec:
  replicas: 3
  selector:
    matchLabels:
      app: csi-iam
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-iam
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: PROXY_ADDRESS_FORWARDING
              value: 'true'
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: domain_name
                  name: security-service-configs
            - name: KEYCLOAK_HOSTNAME
              value: vidaqa.$(BASE_URL)
            - name: KEYCLOAK_LOGLEVEL
              value: WARN
            - name: INFINISPAN_HOST
              value: infinispan-server-hotrod
            - name: INFINISPAN_PORT
              value: '11222'
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_LABELS
              value: app=csi-iam
            - name: JGROUPS_DISCOVERY_PROPERTIES
              value: 'port_range=0,dump_requests=true'
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BOOTSTRAP_SERVERS
                  name: service-configs
            - name: GROUP_ID_CONFIG
              value: register-1
            - name: JAVA_OPTS
              value: >-
                -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m
                -XX:+UseG1GC -XX:+UseStringDeduplication
                -XX:+HeapDumpOnOutOfMemoryError
                -XX:HeapDumpPath=/opt/jboss/memdump  -XX:+PrintGCDetails
                -XX:+PrintGCApplicationStoppedTime
                -XX:+PrintGCApplicationConcurrentTime  -XX:+PrintGCDateStamps
                -Xloggc:gclog.log  -XX:+UseGCLogFileRotation
                -XX:NumberOfGCLogFiles=5  -XX:GCLogFileSize=2000k
                -Djava.net.preferIPv4Stack=true
                -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS
                -Djava.awt.headless=true
            - name: REPORTING_ROUTING_KEY
              value: ''
          envFrom:
            - configMapRef:
                name: iam-service-configs
            - secretRef:
                name: iam-service-secret
          image: 'harbor.cs.local/vidaplus/csi-iam:${parameters.Tag}'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /auth/
              port: http
            initialDelaySeconds: 1200
            timeoutSeconds: 10
          name: csi-iam-app
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https
          readinessProbe:
            httpGet:
              path: auth/realms/master
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 10
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 50m
              memory: 1Gi
      imagePullSecrets:
        - name: regcred
      serviceAccountName: jgroups-kubeping-service-account