apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
#resources:
#- rollout-csi-net-bloodbnk.yaml
#- rollout-csi-bloodbank-ui-rollout-csi-net-bloodbnk-service.yaml

patchesStrategicMerge:
- replica-count.yaml

images:
- name: harbor.cs.local/vidaplus/csi-rms-morgue-java-service
  newTag: 4.1.1.0-a84
