apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: csi-rms-masterdata
  namespace: csi-dev
spec:
  replicas: 1
  strategy:
    canary:
      canaryService: csi-pms-rms-masterdata-canary
      stableService: csi-pms-rms-masterdata
      canaryMetadata:
        annotations:
          role: canary
        labels:
          role: canary
      trafficRouting:
        smi: { }
      steps:
        - setWeight: 10
        - pause:
            duration: "30s"
        - setWeight: 50
        - pause:
            duration: "30m"
      analysis:
        templates:
          - templateName: success-rate
        startingStep: 3 # delay starting analysis run until setWeight: 10%
        args:
          - name: service-name
            value: csi-rms-masterdata
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: csi-rms-masterdata
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-rms-masterdata
        module: rms
        tier: backend
        track: stable
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
    spec:
      containers:
        - env:
            - name: configserver
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
            - name: active_profile
              valueFrom:
                configMapKeyRef:
                  key: active_profile
                  name: service-configs-adt
            - name: CACHE_TYPE
              valueFrom:
                configMapKeyRef:
                  key: cache_type
                  name: service-configs
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: redis_host
                  name: service-configs
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: redis_port
                  name: service-configs
            - name: hostname
              value: csi-pms-rms-masterdata
            - name: FEIGN_HYSTRIX_ENABLED
              value: 'false'
            - name: SPRING_DATASOURCE_TOMCAT_MIN-EVICTABLE-IDLE-TIME-MILLIS
              value: '60000'
            - name: SPRING_DATASOURCE_TOMCAT_MAX-ACTIVE
              value: '225'
            - name: SPRING_DATASOURCE_TOMCAT_MAX-IDLE
              value: '40'
            - name: SPRING_DATASOURCE_TOMCAT_MIN-IDLE
              value: '5'
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_TEMP_USE_JDBC_METADATA_DEFAULTS
              value: 'true'
          envFrom:
            - configMapRef:
                name: service-configs
            - secretRef:
                name: service-configs-secret
            - configMapRef:
                name: service-configs-adt
            - secretRef:
                name: service-adt-secret
          image: >-
            harbor.cs.local/vidaplus/csi-rms-masterdata-java-sev:4.1.21.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /amd-masterdata/actuator/health
              port: http
            initialDelaySeconds: 1200
            timeoutSeconds: 10
          name: csi-rms-masterdata
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /amd-masterdata/actuator/health
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 10
          resources:
            limits:
              memory: 4Gi
            requests:
              cpu: 50m
              memory: 1Gi
      imagePullSecrets:
        - name: regcred
