---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-deployment
spec:
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: "30s"
      - setWeight: 50
      - pause:
          duration: "30s"
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: mynginx
        image: argoproj/rollouts-demo:blue
        ports:
          - containerPort: 80
  #      lifecycle:
  #        postStart:
  #          exec:
  #           command: ["/bin/sh", "-c", "echo 2 > /usr/share/nginx/html/index.html"]
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingress
spec:
  rules:
  - host: sample.web.lk
    http:
      paths:
      - backend:
          serviceName: nginxing-service
          servicePort:  80

---
apiVersion: v1
kind: Service
metadata:
  name: nginxing-service
spec:
  selector:
    app:  mynginx
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
