apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-support-portal
  namespace: csi-perf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-support-portal
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: csi-support-portal
        module: portal
        tier: frontend
        track: stable
    spec:
      containers:
        - env:
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  key: HOST
                  name: support-portal-config
            - name: DB
              valueFrom:
                configMapKeyRef:
                  key: DB
                  name: support-portal-config
            - name: USER
              valueFrom:
                secretKeyRef:
                  key: USER
                  name: support-portal-secret
            - name: PASS
              valueFrom:
                secretKeyRef:
                  key: PASS
                  name: support-portal-secret
            - name: APP_HOST
              value: 'https://csi.perf.cloudsolution.lk/support'
          image: 'harbor.cs.local/vidaplus/csi-support-portal-api:${parameters.Tag}'
          imagePullPolicy: IfNotPresent
          name: csi-support-portal
          ports:
            - containerPort: 3000
              name: http
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 25m
              memory: 256Mi
      imagePullSecrets:
        - name: regcred
