apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
#resources:
#- rollout-csi-net-bloodbnk.yaml
#- rollout-csi-bloodbank-ui-rollout-csi-net-bloodbnk-service.yaml

patchesStrategicMerge:
- replica-count1.yaml

images:
- name: harbor.cs.local/vidaplus/csi-rms-masterdata-java-sev
  newTag: 4.1.19.0 #4.1.21.0
