apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: csi-bloodbank-ui
  namespace: csi-dev
spec:
  replicas: 3
  strategy:
    canary:
      canaryService: rollouts-csi-bloodbank-ui-service-canary
      stableService: rollouts-csi-bloodbank-ui-service-stable
      trafficRouting:
        smi: { }
      steps:
      - setWeight: 20
      - pause:
          duration: "60s"
      - setWeight: 50
      - pause:
          duration: "60s"
      analysis:
        templates:
        - templateName: success-rate
        startingStep: 1 # delay starting analysis run until setWeight: 10%
        args:
        - name: service-name
          value: golang-sample-app
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: csi-bloodbank-ui
      tier: frontend
      track: stable
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: csi-bloodbank-ui
        module: bloodbank
        tier: frontend
        track: stable
    spec:
      containers:
        - image: harbor.cs.local/vidaplus/bloodbank-ui:4.1.11.11
          imagePullPolicy: IfNotPresent
          name: csi-bloodbank-ui
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 25m
              memory: 256Mi
      imagePullSecrets:
        - name: regcred