apiVersion: v1
kind: Service
metadata:
  labels:
    app: healthcare-app
  name: healthcare-app
  namespace: prod
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: healthcare-app
  type: ClusterIP
